### ISSUE TITLE
Ilegal instruction (core dumped)

### ISSUE THREAD

**Issue by PauloBarbeiro** [hvfrancesco/lpmt#5]
I just installed the lpmt on Ubuntu 14.04, and when try to runt it, it returns an error: 
"Ilegal Instruction (core dumped)".

I don't know what is the problem, but thought were good to let you not. I will try to compile it from source, and see what happens. I never worked with Open Frameworks before, so can I ask for some special advises about compiling apps with OF? You know... any dependency, configs, ... things like that.

Thanks,

**Comment by ghost** [comment]
@PauloBarbeiro Have you resolved this issue? I'm having the same problem.

**Comment by PauloBarbeiro** [comment]
No, I had not solve it. Actually I quit to use the software.

**Comment by magdesign** [comment]
use this fork, works under ubuntu:

https://github.com/pierrep/lpmt
