### ISSUE TITLE
Compiling LPMT on RPI2

### ISSUE THREAD

**Issue by magdesign** [hvfrancesco/lpmt#7]
Trying to compile lpmt on RPI2 with of_v0.8.4
I am totally new to openframeworks.
1. Downloaded all depencies listed in addons.make to the /addons directory.
2. Did the export MAKEFLAGS=-j4 PLATFORM_VARIANT=rpi2
3. Navigated to /scripts/linux/ and made a ./compileOF.sh
4. navigated to /apps/lpmt and did a make.
   What I got was:

Makefile:2: ../../../libs/openFrameworksCompiled/project/makefileCommon/Makefile.examples: No such file or directory
make: **\* No rule to make target '../../../libs/openFrameworksCompiled/project/makefileCommon/Makefile.examples'.  Stop.

Any idea?
Would be lovely to see lpmt running on RPI 2

**Comment by Giladx** [comment]
I think this fork was last updated in 10 Apr 2014 Try using OF 0.8 you can download it from the OF archive. remember to delete the obj folder (inside addons before you build in 0.8)
good luck

**Comment by magdesign** [comment]
I tried it with of 0.8.0 same error.

What I now did was using Foaly's fork: https://github.com/Foaly/lpmt
Set the openframeworks path in `config.make`
did the `export MAKEFLAGS=-j4 PLATFORM_VARIANT=rpi2`
and it finally compiles a bit on of_0.8.4 (but I'm still not able to fully compile it: https://github.com/Foaly/lpmt/issues/15)
It seems to be an issue with the ofxSimpleGuiToo: https://gist.github.com/magdesign/e586a8a4516492167d98

Any idea how to solve this?

**Comment by magdesign** [comment]
A while ago  you wrote on your facebook: 
"preliminary LPMT port to Raspberry Pi, amazing little platform indeed"

Is there any beta code available, would love it and I'm sure many other people too...

**Comment by Giladx** [comment]
this announce was written on HVA facebook
but I do can try to compile my own fork to my Pi(B+) and let you know ..

**Comment by magdesign** [comment]
Yes, please try to compile this..... looking forward to hear a positive feedback :-)

**Comment by magdesign** [comment]
Is there anyone successfully compiled LPMT on RPI or any other ARM board?
Or is this project more or less declared as dead?
